### ISSUE TITLE
import types of schema A into schema B

### ISSUE THREAD

**Issue by bsr203** [neelance/graphql-go#1]
Thank you for more idiomatic graphql option for go. 

I am currently using https://github.com/graphql-go/graphql, though it is incredibly verbose, I could structure the schema so it is kept at module level. 

I see one thread in `graphql-js` regarding the same, in which lee says
https://github.com/graphql/graphql-js/issues/223

> If you're using the schema language to build a schema than you need to first combine it into a single string before calling buildSchema. That typically is a nice developer experience for small to medium sized schema, though for more complex schema we recommend building the schema programmatically. Even in this case you still need to collect all the types to assemble the schema. A similar operation to collecting all the strings before calling buildSchema

I wonder what is the best approach you propose with this library. Any plan for incrementally building the schema by registering the graphql schema and resolve functions for isolated modules ? 

thanks again for providing this library.

**Comment by neelance** [comment]
Hi @bsr203, thanks for looking into my project.

My current plan is to not expose the schema data structures. The only way to create a schema is via the schema language. However, at some point I want to add a way to load multiple schema strings and have one schema import types from another schema. Then each schema still has its own namespace, but you can use them together as one big schema.

Does that sound good to you? Do you need such a feature soon?

**Comment by bsr203** [comment]
Thank you for the quick response. What you described would be ideal, and I am in no rush :-) I just wanted to make sure it is considered so we may add it in the future without much of breaking the existing implementation. Do you want to keep this open till it is implemented?

Thank you for all your effort on this.

**Comment by neelance** [comment]
Yes, we can keep it open. I've changed the title accordingly.

**Comment by bsr203** [comment]
Just adding reference to an approach I saw.
[apollostack/graphql-tools](https://github.com/apollostack/graphql-tools) allows easy mocking of resolvers, and uses graphql language and resolver very similar to this library. see the [example](https://github.com/apollostack/graphql-tools#example) on readme. There is a [section](http://dev.apollodata.com/tools/graphql-tools/generate-schema.html#modularizing) about modularization.

I currently modularize the schema by exporting the schema of the module and concatenate before pass to `ParseSchema`. Resolvers work naturally. AFAIK, the order of type def in schema doesn't matter, hence not much trouble splitting and referencing the schema. I am happy with this approach and you are free to close this.

**Comment by neelance** [comment]
Happy to hear that! String concatenation sounds like a very clear and simple way of implementing modularization. Do you see any potential limitations?

**Comment by bsr203** [comment]
not really, it works great for me as the order of types within schema doesn't matter. Also, namespacing is [not supported ](https://github.com/graphql/graphql-js/issues/221#issuecomment-157481861) by graphql. There been [need for this](https://github.com/graphql/graphql-js/issues/490), but for the moment, we are good :-)

**Comment by neelance** [comment]
Cool, I'll close this issue. Maybe I'll even replace `SchemaBuilder` with some simpler API at some point.
