### ISSUE TITLE
input relies on struct fields rather than methods?

### ISSUE THREAD

**Issue by amozoss** [neelance/graphql-go#11]
I changed the reviewInput to have a method `Stars()` instead of the field `Stars`. 
```
diff --git a/example/starwars/starwars.go b/example/starwars/starwars.go
index 23eb068..0bd6de6 100644
--- a/example/starwars/starwars.go
+++ b/example/starwars/starwars.go
@@ -357,7 +357,7 @@ func (r *Resolver) CreateReview(args *struct {
        Review  *reviewInput
 }) *reviewResolver {
        review := &review{
-               stars:      args.Review.Stars,
+               stars:      args.Review.Stars(),
                commentary: args.Review.Commentary,
        }
        reviews[args.Episode] = append(reviews[args.Episode], review)
@@ -646,6 +646,10 @@ func (r *pageInfoResolver) HasNextPage() bool {
 }
 
 type reviewInput struct {
-       Stars      int32
+       the_stars  int32
        Commentary *string
 }
+
+func (r *reviewInput) Stars() int32 {
+       return r.the_stars
+}
```

```
panic: method "CreateReview" of *starwars.Resolver: missing argument "stars"

goroutine 1 [running]:
panic(0x2b9d60, 0xc420143c00)
        /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
main.init.1()
        /Users/dan/go/src/github.com/neelance/graphql-go/example/starwars/server/server.go:18 +0xc2
main.init()
        /Users/dan/go/src/github.com/neelance/graphql-go/example/starwars/server/server.go:89 +0x47
```

  Is this the expected behavior for input structs?

**Comment by neelance** [comment]
I don't really get what you're trying to do. `reviewInput` is an *input* argument, so something that is provided by the GraphQL query. How do you expect it to set `the_stars`? There is no setter anywhere and it is not exported, thus unavailable to reflection.

**Comment by amozoss** [comment]
Sorry I wasn't very clear. I was just confused by the error message.

I wasn't trying to do anything specific, I was following the pattern of the resolvers (such as `humanResolver`) for my _input_ argument. In my case, I hadn't specified the fields yet on the struct, but instead had made methods (changing the starwars example above just provided an example of what I had done in my own project). It seemed to me like the issue was in the `args` to `CreateReview` rather than putting fields on `reviewInput`. It makes sense now that you've explained it, thanks.
