### ISSUE TITLE
Magellan GraphQL comparison

### ISSUE THREAD

**Issue by saviodo5591** [neelance/graphql-go#115]
Does anyone know of the differences between this repo and the Magellan GraphQL repo? I was thinking of switching over to that repo, there seems to be more documentation there and I'm curious to know if anyone has any experience with both repos

**Comment by lpalmes** [comment]
Hey @saviodo5591, i've been looking at it but it seems that they are both different packages, i was looking for subscriptions in graphql, i will try it out and in any case let you know how it goes, thanks for sharing it!
