### ISSUE TITLE
why pointers

### ISSUE THREAD

**Issue by jackielii** [neelance/graphql-go#123]
Hi,

Tried really hard to search for documentation on why we need to use Pointers throughout. Can someone elaborate a bit?

Regards,

**Comment by TheWinds** [comment]
> use pointer you can define  **optional parameters**.

for example 
in schema
```
type Query {
user(id:Int): [User]!
...
type Mutation {
startTest(paperID:Int!,userID:Int!):Int!
...
```

then the arguments structs should be define like this
```
...
args *struct{ ID *int32 }
...
args *struct {
	PaperID int32
	UserID  int32
}
```

**Comment by jackielii** [comment]
@TheWinds  Yep, after a few days working with it, I think you're absolutely right
