### ISSUE TITLE
Go Get Returned a non-zero code: 1

### ISSUE THREAD

**Issue by cmwhited** [neelance/graphql-go#139]
**Bug Report**

When installing the package via go get from a Dockerfile, get error:
`package context: unrecognized import path "context"`
`The command '/bin/sh -c go get github.com/neelance/graphql-go' returned a non-zero code: 1`

**Comment by vergenzt** [comment]
Looks like the `context` package was introduced in Go 1.7. What version of Go are you building in?

I think the resolution to this ticket is likely just to document that this library requires a minimum Go version of 1.7.

**Comment by cmwhited** [comment]
My current go version is `go version go1.9.1 darwin/amd64`. I wonder if it is the go version being utilized in my docker container.

**Comment by cmwhited** [comment]
I have the latest docker golang image provided by: `FROM google/golang` which appears to be 1.8

**Comment by rideliner** [comment]
`docker run --rm -it google/golang go version` shows that it is version 1.5.

I think you may be looking for `FROM golang` which has the latest versions. Here is a [reference](https://hub.docker.com/_/golang/) of available tags (i.e., versions).

**Comment by cmwhited** [comment]
Thanks guys. I switch to `golang:1.10-rc` and it worked fine. I will close this issue.
