### ISSUE TITLE
define schema programmatically

### ISSUE THREAD

**Issue by bsr203** [neelance/graphql-go#14]
Hi,

akin to how custom scalars can be defined, is it possible to define graphql types programmatically. One use case is to generate schema definition through code generation, say with the resolver struct and some struct tags.  This may be related to https://github.com/neelance/graphql-go/issues/1 , but it may also help with modularization if a resolver also can set along with type registration. What do you think?

Thanks,
bsr.

**Comment by neelance** [comment]
Yes, this sounds very similar to #1. As already mentioned there, I would prefer to combine multiple textual schema definitions. Programmatically defined GraphQL types would conflict with the "minimal API" goal stated in the Readme.

> it may also help with modularization if a resolver also can set along with type registration

One property of graphql-go is that there is no 1-to-1 relationship between GraphQL types and Go types. The Go type of the resolver is completely determined by how you got that resolver (e.g. the return type of the parent resolver's method). Thus I think what you're suggesting does not fit into this architecture.

Modularization is also important to me, I'm sure we'll find ways to make it possible in a simple and non-magic way.

**Comment by neelance** [comment]
> One use case is to generate schema definition through code generation, say with the resolver struct and some struct tags.

Imho a schema should not be generated. The schema is the ground truth, the simplest way to express how your API looks like. The implementations are then matched against the schema.

**Comment by bsr203** [comment]
I agree, since the graphql schema is very minimal and clean. I would start trying in my project and see how it works. Also, curious about the relay example as my project is similarly structured and would be a great example to follow. thank you for all the hard work. cheers.
