### ISSUE TITLE
Array as argument fails

### ISSUE THREAD

**Issue by nicksrandall** [neelance/graphql-go#19]
Looking at the graphql spec, this is no indication that this is officially supported or not but I have a use case where I would like to pass an array as an argument to a resolver. Currently, I'm getting a TODO panic error when I do this:
https://github.com/neelance/graphql-go/blob/3b7efd5cb6e73337e26a67ca05750b6e1b02320e/internal/exec/exec.go#L315

As far as I can tell, that type switch needs to be able to handle a `*common.List` item.

Here is my use case:
```graphql
{
  approvals(status: [PENDING, APPROVED]) {
    type
    title
    amount
    attachments
    submitter {
      firstName
      lastName
      title
    }
  }
}
```

**Comment by nicksrandall** [comment]
This also fails in the same way if an array is a field on an input argument as well.

**Comment by bsr203** [comment]
I think list is supported as input value. from [spec](https://facebook.github.io/graphql/#sec-Input-Values)

> Field and directive arguments accept input values of various literal primitives; input values can be scalars, enumeration values, lists, or input objects.

**Comment by nicksrandall** [comment]
@neelance can you give me some direction on how to fix this error? I'm happy to contribute. Also, I'm currently blocked on this.

**Comment by neelance** [comment]
See my comment on #21. Just tell me if you're still stuck, I'll then give it a try myself.

**Comment by nicksrandall** [comment]
@neelance I'm pretty stuck. I'm having a hard time coming up with an elegant solution.

**Comment by nicksrandall** [comment]
As a temporary work around... I have made this awful change in my local version:

line 323:
```go
case *common.List:
	fe.fieldPacker = &slicePacker{
		sliceType: sf.Type,
		nonNull:   nonNull,
        }
```

line 775:
```go
type slicePacker struct {
	sliceType reflect.Type
	nonNull   bool
}

func (e *slicePacker) pack(value interface{}) reflect.Value {
	v := reflect.New(e.sliceType).Interface()
	b, _ := json.Marshal(value)
	json.Unmarshal(b, &v)
	s := reflect.ValueOf(v)
	if e.nonNull {
		s = reflect.Indirect(s)
	}
	return s
}
```

**Comment by neelance** [comment]
It turned out to be a bit more work than I initially expected. Please give it a try and tell me if you see any issues. Thanks for trying to contribute with that PR though!

**Comment by nicksrandall** [comment]
Thank you! I'll test and let you know if I find any issues.

**Comment by nicksrandall** [comment]
@neelance I'm still getting the panic error when I have an input item that has a field that is an array. I'm hitting the same  "TODO" panic because the `makePaker` type switch doesn't have a case for `*schema.Object`. Can we re-open this issue? Or would you prefer that I create a new one?

**Comment by neelance** [comment]
@nicksrandall I think you might be using a `type` (object) type instead of an `input` type. I've added a proper error message for that case via fff173b.
