### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by bsr203** [neelance/graphql-go#2]
Hello,

It would be great to see how feature compliant is this library with the graphql spec. Is it possible to maintain an issue or project to get an idea of when one can use certain feature.

thanks.
bsr

**Comment by neelance** [comment]
I just started the project recently, so there is a lot of WIP. But feel free to list the features/bugs that you'd like to see tackled first and I'll see what I can do. :-)

**Comment by bsr203** [comment]
Thank you. I would list out the features needed for my app to work, which currently uses [graphql-go](https://github.com/graphql-go/graphql)

**Comment by bsr203** [comment]
hi,

There are many frontend implementation for `todo mvc` app. here is an official [relay example](https://github.com/relayjs/relay-examples/tree/master/todo). I did a while back the backend for another go graphql library [here](https://github.com/tmc/graphql/pull/3/files), and do you think it is worthwhile to use it as an example so we can just use the relay app for frontend ? 

here is the schema generated with the [relay app](https://github.com/relayjs/relay-examples/blob/master/todo/scripts/updateSchema.js#L37)

```
schema {
  query: Root
  mutation: Mutation
}

input AddTodoInput {
  text: String!
  clientMutationId: String
}

type AddTodoPayload {
  todoEdge: TodoEdge
  viewer: User
  clientMutationId: String
}

input ChangeTodoStatusInput {
  complete: Boolean!
  id: ID!
  clientMutationId: String
}

type ChangeTodoStatusPayload {
  todo: Todo
  viewer: User
  clientMutationId: String
}

input MarkAllTodosInput {
  complete: Boolean!
  clientMutationId: String
}

type MarkAllTodosPayload {
  changedTodos: [Todo]
  viewer: User
  clientMutationId: String
}

type Mutation {
  addTodo(input: AddTodoInput!): AddTodoPayload
  changeTodoStatus(input: ChangeTodoStatusInput!): ChangeTodoStatusPayload
  markAllTodos(input: MarkAllTodosInput!): MarkAllTodosPayload
  removeCompletedTodos(input: RemoveCompletedTodosInput!): RemoveCompletedTodosPayload
  removeTodo(input: RemoveTodoInput!): RemoveTodoPayload
  renameTodo(input: RenameTodoInput!): RenameTodoPayload
}

interface Node {
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

input RemoveCompletedTodosInput {
  clientMutationId: String
}

type RemoveCompletedTodosPayload {
  deletedTodoIds: [String]
  viewer: User
  clientMutationId: String
}

input RemoveTodoInput {
  id: ID!
  clientMutationId: String
}

type RemoveTodoPayload {
  deletedTodoId: ID
  viewer: User
  clientMutationId: String
}

input RenameTodoInput {
  id: ID!
  text: String!
  clientMutationId: String
}

type RenameTodoPayload {
  todo: Todo
  clientMutationId: String
}

type Root {
  viewer: User
  node(id: ID!): Node
}

type Todo implements Node {
  id: ID!
  text: String
  complete: Boolean
}

type TodoConnection {
  pageInfo: PageInfo!
  edges: [TodoEdge]
}

type TodoEdge {
  node: Todo
  cursor: String!
}

type User implements Node {
  id: ID!
  todos(status: String = "any", after: String, first: Int, before: String, last: Int): TodoConnection
  totalCount: Int
  completedCount: Int
}
```

**Comment by bsr203** [comment]
I will raise issues separately and provide above todo example as a PR when I get it to work. thanks.

**Comment by neelance** [comment]
@bsr203 I've started working on this myself, since it was a good idea. Let's avoid doing the same work twice. I'll commit it soon and give you an update then.

**Comment by bsr203** [comment]
Thanks. I can do the front end stuff as setting up relay could be too time consuming. If you could do the backend, I could take up the rest. thanks again for all your effort. getting super excited :-)

**Comment by bsr203** [comment]
Hi. I saw you starred react-router-relay. @taion commented in few threds about possibly no support for react-router 4, and he is working on alternatives https://github.com/4Catalyzer/found
https://github.com/4Catalyzer/found-relay

I recently migrated from react-router to http://grahammendick.github.io/navigation/
There are plenty of [samples](https://github.com/grahammendick/navigation/tree/master/NavigationReact/sample), including relay, hot reloading. The relay example is not idiomatic as the author isn't familiar with relay but I could migrate my app without any issue. HTH.

**Comment by neelance** [comment]
Thanks for making me aware. :)

**Comment by bsr203** [comment]
@neelance sorry for bugging you on this, but did you face any difficulty doing the backend which supports relay. It would be great help before I undergo the migration to this library. thank you.

**Comment by lpalmes** [comment]
@neelance Sorry for the noise. But I managed to add it to graphql.org. Just to let you know.
https://github.com/graphql/graphql.github.io/pull/203

**Comment by neelance** [comment]
@lpalmes Cool, thanks for your effort!

**Comment by lpalmes** [comment]
@neelance. I wanted to know if we could get some help with documentation. I couldn't resolve an array of structs because i have to pass a pointer back. And I couldn't figure it out. Maybe it was me. Thanks for working on this

**Comment by bsr203** [comment]
@lpalmes https://github.com/chentsulin/awesome-graphql#lib-go may be a good place as well, if you got time for it.

**Comment by lpalmes** [comment]
Oh. Thanks @bsr203 Will do

**Comment by lpalmes** [comment]
I already have used github.com/graphql-go/graphql. And successfully. But it was a bit verbose. So I decided to try this one. And I'm lacking some understanding right now I guess. Future docs will help a lot

**Comment by bsr203** [comment]
@lpalmes I am also in the learning phase, and you might have already seen, the [example](https://github.com/neelance/graphql-go/tree/master/example/starwars) is quite good. Note sure whether you are looking something along [this](https://github.com/neelance/graphql-go/blob/master/example/starwars/starwars.go#L375)  or [this](https://github.com/neelance/graphql-go/blob/master/example/starwars/starwars.go#L376)

**Comment by lpalmes** [comment]
I've built a introduction while i will try to explain graphql-go, and how to use it, at first it was a bit difficult for me as you can see above, so i would like to ease the pain to newcomers. If you see something wrong or anything please let me know, i want to help this project given that i had gotten so much from it. Thanks!
https://github.com/lpalmes/graphql-go-introduction
