### ISSUE TITLE
interface resolver

### ISSUE THREAD

**Issue by bsr203** [neelance/graphql-go#23]
Hello,

I am trying to implement `Node` interface as per the relay spec.  @saward gave an [example](https://github.com/neelance/graphql-go/pull/16#issuecomment-260074140), and as I see in the [starwars example](https://github.com/neelance/graphql-go/blob/master/example/starwars/starwars.go#L378),  I need to implement `To*` methods for all types which implements the interface. This makes the interface grow with the number of type implements it, and not able to split the resolver into multiple packages due to circular reference.

I wonder is it possible to check the method set of the concrete type, instead of the interface. In the below code, `Node` method of root resolver returns type resolver which implements `NodeResolver` interface (a single method), but has other methods to resolve the concrete type. 

thank you,
bsr.

```
var Schema = `
schema {
    query: Query
}

interface Node {
    id: ID!
}

type Query {
    node(id: ID!): Node
}

type Human implements Node {
    id: ID!
}

type Droid implements Node {
    id: ID!
}
`

type NodeResolver interface {
    ID() graphql.ID
}

type Resolver struct{}

func (r *Resolver) Node(ctx context.Context, args *struct{ ID graphql.ID }) (NodeResolver, error) {
  tp := getTypeFromID(args.ID)
  switch tp {
    case "human":
      return &HumanResolver{getHumanOnID(string(args.ID))}
    case "droid":
      return &DroidResolver{getDroidOnID(string(args.ID))}
    default:
      return nil, fmt.Errorf("no fetcher for %s", tp)
  }
}
```

**Comment by neelance** [comment]
You are right. The current way did not permit any splitting into packages because it would always cause a cyclic dependency.

I've been thinking about it for a bit and I've come up with a new approach, see a15deed. Notice that I did not modify graphql-go itself, it is only a better way to structure the Go types that still resolve the GraphQL types in the same way.

Does it look good to you?

**Comment by bsr203** [comment]
thanks a ton for quick solution. I will try out in an hour, and get back to you. thanks again.

**Comment by bsr203** [comment]
that works great. thank you.
