### ISSUE TITLE
panic on unexported field

### ISSUE THREAD

**Issue by bsr203** [neelance/graphql-go#24]
I got a panic, where the schema is built without error. Ideally this error should reported during parse time. I am still hunting it down, but proper error message would report which struct has unexported field. I hope you can identify the location with the stack trace.

```
2016/11/18 15:52:27 graphql: graphql: panic occured: reflect: reflect.Value.Set using value obtained using unexported field
goroutine 10 [running]:
github.com/neelance/graphql-go/internal/exec.(*request).handlePanic(0xc4201d4a00)
	/Users/bsr/.../external/src/github.com/neelance/graphql-go/internal/exec/exec.go:392 +0x123
panic(0x57b880, 0xc420103760)
	/usr/local/go/src/runtime/panic.go:458 +0x243
reflect.flag.mustBeAssignable(0x1b6)
	/usr/local/go/src/reflect/value.go:225 +0x1a2
reflect.Value.Set(0x5552a0, 0xc420024300, 0x1b6, 0x5552a0, 0xc42047ed50, 0x16)
	/usr/local/go/src/reflect/value.go:1327 +0x2f
github.com/neelance/graphql-go/internal/exec.(*structPacker).pack(0xc42046d000, 0x5acc60, 0xc4200452f0, 0x5acc60, 0xc42047ec60, 0x936a20)
	/Users/bsr/.../external/src/github.com/neelance/graphql-go/internal/exec/exec.go:749 +0x2b3
github.com/neelance/graphql-go/internal/exec.(*fieldExec).execField2(0xc42046aff0, 0x933400, 0xc42047ecf0, 0xc4201d4a00, 0xc4201d4900, 0x5c0860, 0x983ae8, 0x16, 0x936a20, 0xc42048e
```

**Comment by bsr203** [comment]
It happens when used unexported field, `review`, like below
```
func (r *Resolver) CreateReview(args *struct {review  *reviewInput}) *reviewResolver 
```

works fine if use exported field
```
func (r *Resolver) CreateReview(args *struct {Review  *reviewInput}) *reviewResolver 
```

it also gives same error, if any of the field of `reviewInput` is unexported as well.

if it is  hard to inspect, we may close this with a mention in the docs.

thanks.

**Comment by nicksrandall** [comment]
What behavior were you expecting? Just like any other encoding package, you can't unmarshal data into a struct with unexported fields. Seems to me like the expected behavior for Go project? Am I wrong?

**Comment by neelance** [comment]
I think this is only about raising that error already on startup, not only when the field is being used.
