### ISSUE TITLE
GraphQL spec version

### ISSUE THREAD

**Issue by xzyfer** [neelance/graphql-go#35]
It would be good to have some indication of what version of the GraphQL spec this implementation is currently aligned with. The current version is [graphql-js@v0.8.2][1].

[1]: https://github.com/graphql/graphql-js/releases/tag/v0.8.2

**Comment by nicksrandall** [comment]
@xzyfer That is the version of the javascript implementation. The latest spec for graphql can be found here: [(Oct. 2016)](https://facebook.github.io/graphql/). I agree that it would be helpful to identify how compliant this implementation is.

**Comment by neelance** [comment]
The goal definitely is 100% support for the latest spec. It is hard to say how compliant graphql-go currently is, since there is no official test suite. If you see any deviation from the spec please file an issue and I'll fix it asap.

**Comment by xzyfer** [comment]
Specifically I think differentiating between a goal and an expectation.

Stating it's goal suggests you're actively working on catching to spec, with no real indication of the current progress. IMHO it would help consumers to know that current status is (believed to be) compatible with (Oct. 2016).

**Comment by neelance** [comment]
I'm a pragmatic person. I'm not going through the spec step-by-step, I'm rather implementing what I currently need or issues that others report. To determine some concrete status of compatibility we either need an official GraphQL test suite or someone has to go through the spec step-by-step and verify. That's not on my TODO list. In the readme I'll change "goals" into "features" as soon as I am confident enough.
