### ISSUE TITLE
Validation test

### ISSUE THREAD

**Issue by antonikonovalov** [neelance/graphql-go#38]
Hi!

Good work :)))

I checked http://graphql.org/learn/validation/ on starwars and find failed cases:

```
{
  hero {
    ...NameAndAppearancesAndFriends
  }
}

fragment NameAndAppearancesAndFriends on Character {
  name
  appearsIn
  friends {
    ...NameAndAppearancesAndFriends
  }
}
```

server didn't check recursion and go to infinity loop

```
{
  hero {
    name {
      firstCharacterOfName
    }
  }
}
```
expected - "Field \"name\" must not have a selection since type \"String!\" has no subfields."

will be best if you include that tests - https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsValidation-test.js

**Comment by neelance** [comment]
The validation checks mentioned here have been implemented. I am still working on a few others, see commented lines on https://github.com/neelance/graphql-go/blob/master/internal/tests/testdata/export.js#L57-L81.

**Comment by neelance** [comment]
Query validation is now fully implemented.
