### ISSUE TITLE
Hang while processing invalid introspection query

### ISSUE THREAD

**Issue by titanous** [neelance/graphql-go#4]
I've been fuzzing with go-fuzz, and it found this (apparent) hang: https://gist.github.com/titanous/56d6628389b88a8a50966f30517b0c21

I'm happy to dig into this more and fix it, but I thought I'd open an issue early as I'm not yet familiar with the codebase.

**Comment by titanous** [comment]
Ah, it looks like this is not a bug, just an unimplemented error handler: https://github.com/neelance/graphql-go/blob/c28891d831baca59c10027b31a67deda775b3fff/internal/exec/exec.go#L527

**Comment by neelance** [comment]
Hey @titanous, thanks for reporting this and sorry for my late reply.

While the error handling is not yet in the shape I want it to be, it should still not hang. There might be some panic that is then recovered by the surrounding error handler, but there should be no infinite loop or recursion.

May I ask you to track this down a bit further? Maybe some test case that is a bit simpler than what's in that gist? :)

**Comment by neelance** [comment]
Closing this for now. We can reopen it if you have further feedback.
