### ISSUE TITLE
Input List Coercion 

### ISSUE THREAD

**Issue by JustinJudd** [neelance/graphql-go#41]
I stumbled across [this conversation for a question for graphQL-relay](https://github.com/graphql/graphql-relay-js/issues/20#issuecomment-135887330), where they point out that the
[GraphQL Spec](http://facebook.github.io/graphql/#sec-Lists) details that list inputs should be able to handle a single value of the type that can be used in the list. I have been attempting this, for a input of `[String!]` but am getting the following error

`graphql: graphql: panic occured: interface conversion: interface is string, not []interface {}`

**Comment by neelance** [comment]
Thanks for reporting! :)

**Comment by JustinJudd** [comment]
Thanks for the amazingly quick fix. Tested the list coercion as well as the new scalar interface and both work great.

Thanks!
