### ISSUE TITLE
define scalar type in schema

### ISSUE THREAD

**Issue by bsr203** [neelance/graphql-go#43]
I use custom scalar, and it needed to be defined to use with other javascript backend.
```
scalar Time
scalar JSON
```
 Otherwise, it gives error along the lines of, `unreferenced type Time`, etc.

but, `graphql-go` gives error

` ERROR: graphql: syntax error: unexpected "scalar", expecting "schema", "type", "enum", "interface", "union" or "input" (line 7, column 9)
`

can we allow `scalar` to be valid type?

**Comment by neelance** [comment]
Isn't this just resolved by my latest change?

**Comment by bsr203** [comment]
sorry, haven't tried with it yet. will get back tomorrow.

**Comment by bsr203** [comment]
Thanks it works great. One question. Is it strictly require the resolver output type to be `graphql.Time`. It works if I use `time.Time`. I may change later, but wonder is it ok for now?

[ref](https://github.com/neelance/graphql-go/commit/2b513d7e6c46b01de0cbcaeb1b68424dd3c043be#diff-d7906d668830f592334a2a80cf6d298cR39)

**Comment by neelance** [comment]
The Go type has to implement `ImplementsGraphQLType` and `UnmarshalGraphQL`, which `time.Time` does not. If it works in your case, then something is weird.

**Comment by bsr203** [comment]
sorry for not being clear. In my case, it does implement the interface, but the resolver returns the `raw` type.

so instead of the new way in [this diff](https://github.com/neelance/graphql-go/commit/2b513d7e6c46b01de0cbcaeb1b68424dd3c043be#diff-d7906d668830f592334a2a80cf6d298cR39)

```
 func (r *timeResolver) AddHour(args *struct{ Time graphql.Time }) graphql.Time {
   return graphql.Time{Time: args.Time.Add(time.Hour)}
 }
```

the old way of returning non graphql type works

```
func (r *timeResolver) AddHour(args *struct{ Time time.Time }) time.Time {
	return args.Time.Add(time.Hour)
}
```

lot of changes to re-write all the resolvers now, and wonder it's ok to keep that way for some time.

**Comment by neelance** [comment]
Ah yes, that might work right now since `time.Time` ist just fed to `json.Marshal` unchecked. However, I'll soon only allow basic mappings, e.g. `Int` to `int32` and types with `ImplementsGraphQLType`, so that will not work any more. This is so we have a proper check that the Go type is actually meant for implementing a certain GraphQL type. Maybe there will also be a `MarshalGraphQL` method, since I'd like to keep GraphQL separate from JSON semantics (which is how the GraphQL spec is designed).

**Comment by bsr203** [comment]
thanks for the explanation. I would soon change to follow the right type to return. thanks again.
