### ISSUE TITLE
Weird dependency

### ISSUE THREAD

**Issue by nicksrandall** [neelance/graphql-go#44]
Is this line correct? I feel like you meant to inject the internal github package? Its currently breaking my build.

https://github.com/neelance/graphql-go/blob/master/internal/exec/packer.go#L11

**Comment by shurcooL** [comment]
`errors` is a pretty well known Go package.

https://godoc.org/github.com/pkg/errors

> It's currently breaking my build.

What's your error? Perhaps you need to `go get` it?

**Comment by nicksrandall** [comment]
@shurcooL yes, the problem was that I needed to `go get` it but @neelance is using it in the exact same way that he uses his internal `errors` package. It just feels like `go imports` choose the wrong package in this case.

**Comment by shurcooL** [comment]
> It just feels like `goimports` choose the wrong package in this case.

Ah, that might've been the case then.
