### ISSUE TITLE
Expose the Go resolvers for __schema

### ISSUE THREAD

**Issue by tonyghita** [neelance/graphql-go#46]
I'd like to be able to introspect a schema that is defined in the graphql schema language.
```go
b, err := ioutil.ReadFile("schema.graphql")
if err != nil {
  log.Fatalln("Unable to read schema file", err)
}

schema, err := graphql.ParseSchema(string(b), &Resolver{})
if err != nil {
  log.Fatalln(err)
}

// TODO: ability to introspect schema 
```
Being able to iterate over the schema after it's been parsed would help in writing code generators for resolvers.

**Comment by neelance** [comment]
Done. See https://godoc.org/github.com/neelance/graphql-go#Schema.Inspect
