### ISSUE TITLE
Panics with invalid/nonsensical queries in example

### ISSUE THREAD

**Issue by dabfleming** [neelance/graphql-go#5]
I'm new to GraphQL and working toward setting up a server in Go. Was playing around with the example server and find that the server panics with some invalid or nonsensical queries. I would expect either a parsing error or more graceful failure.

Problem queries:
```
{
  character(id: "1000") {
    id
    name
    friends
  }
}
```

```
{
  character(id: "1000")
}
```

Note that adding matched braces after friends or character causes it to run without issue.

**Comment by neelance** [comment]
Yes, it is true that the validation phase needs to be improved. So far I've more focused on the error reporting of inconsistencies between the schema and the resolver. My plan here is to reuse the tests for validation of the graphql-js project.

**Comment by neelance** [comment]
This and several other query validation rules have been implemented now.
