### ISSUE TITLE
ENUM is being quirky

### ISSUE THREAD

**Issue by EmperorEarth** [neelance/graphql-go#51]
I may give a full example later to help you reproduce this but my current code isn't open-source.

I have an `ENUM` type `Bar` that is also an argument for a GraphQL mutation of a custom type `Foo`.

schema looks like this:
```
type Mutation {
	createFoo(blurb: String!, bar: Bar): Foo
}
enum Bar {
	Bar1
	Bar2
	...
	BarN
}
```

root resolver like this:
```
type Resolver struct {
	db *sql.DB
}
func (r *Resolver) CreateFoo(args *struct{ Blurb, Bar string }) *FooResolver { ... }
```

type resolver like this:
```
type FooResolver struct {
	db *sql.DB
	id uuid.UUID
}
func (r *FooResolver) Bar() *string {
	...
	return  &barString
}
```

> Side note, would prefer
> ```
> func (r *FooResolver) Bar() string {
> 	...
> 	return  barString
> }
> ```
> or better
> ```
> func (r *FooResolver) Bar() Bar {
> 	...
> 	return  bar
> }
> ```
> but that doesn't compile on different errors
> moving back to the main timeline

If I try to compile that, it fails with an error: `Failed to parse raw schema: method "CreateFoo" of *main.Resolver: field "Bar": wrong type, expected *string`

No problem, I'll adapt the `Resolver.CreateFoo(...)` method like so:
```
func (r *Resolver) CreateFoo(args *struct{
	Blurb string
	Bar *string
}) *FooResolver { ... }
```

Then, when I run a query, I get this response:
```
{
  "data": {
    "createFoo": null
  },
  "errors": [
    {
      "message": "could not unmarshal \"Bar1\" (string) into *string: incompatible type"
    }
  ]
}
```

By commenting out [these lines](https://github.com/neelance/graphql-go/blob/master/internal/exec/packer.go#L47-L49) and going back to my original code, it compiles and handles the mutation and the queries. What am I missing or is there a bug in the ENUM reflection?

**Comment by EmperorEarth** [comment]
After talking with you and playing with your port a bit more, @neelance, I have an idea.

Without fully understanding your code, I think you are trying to enforce two rules:

- In your schema parser, if a `type` is `nullable`, then its resolver must have a pointer return, with a `nil` translating to `null`
- In your `exec`utor, if a `type` is custom, then it `unmarshals` using a `non-nullable` type

These two rules combined with a third fact, `ENUM`s aren't a type in Go, means that `nullable` `ENUM`s are trapped between your rules.

My guess might be way off base or I might have explained this poorly. But perhaps it's a place to start.

**Comment by neelance** [comment]
Hey, thanks for reporting this. Could you please try again with the latest master? I did some changes, but I'm not sure if it fully resolves this.

**Comment by EmperorEarth** [comment]
Can confirm, this has been fixed, thanks so much
