### ISSUE TITLE
return structured errors

### ISSUE THREAD

**Issue by acornejo** [neelance/graphql-go#52]
Suppose I am sending a mutation with a collection of fields, and I need to validate them (i.e. check that string is an email, integer is valid age, string is valid phone number, string is valid credit card, etc).

Ideally, I would like to be able to returned a structured error when there were errors, something along the lines of:

```
{
   errors: {
      'email': 'Invalid email address'
      'contact.phone': 'Invalid phone number',
      'payment.creditcardnumber': 'This looks like an american express, not accepted here'
      ...
   }
}
```

Producing the json above is quite simple (depends on what validation library you use for your inputs, there are plenty of them out there). However, reading the examples its not clear to me that graphql-go it is possible to write a resolver that returns such a structured error.

**Comment by bsr203** [comment]
hi. I also had the same requirement, but graphql spec defines a format for errors, and cannot return arbitrary structure. see https://facebook.github.io/graphql/#sec-Errors

so, I just return a custom error (my data as json as the Error() value ) and this library serialize it and available at the client as `message` field.

```
type ErrorResponse struct {
 ......
}

func makeErrorResponse(ctx context.Context, err error) error {
	if err == nil {
		return nil
	}
  ...
  // populate ErrorResponse with type asserting `err` to my custom errors (Validation, ...)
//  encode ErrorResponse
b, err := json.Marshal(resp)
	if err != nil {
...
}
	return fmt.Errorf("%s", b)
}
```

check also the last commit by @nicksrandall as it also address the same issue. I am yet to check it out. HTH

**Comment by neelance** [comment]
Please see the comments/resolution on https://github.com/neelance/graphql-go/pull/49.
