### ISSUE TITLE
Recursive Input Object

### ISSUE THREAD

**Issue by EmperorEarth** [neelance/graphql-go#54]
**What I'm trying to do**
I'm writing a service (no Relay), where users can generate custom filters that they can later apply on our dataset. These filters can be nested recursively. The idea is to be able to create filters that can compose other filters, whether from the same input or from existing filters. So we can filter our data for `((A || B) && (C || D))`, or other compositions.

**How do I write the go glue for the following graphql schema? (the mutation code)**

`schema.graphql`
```
type Query {
	boolFilter(id: ID!): BoolFilter
}
type Mutation {
	createBoolFilter(input: BoolFilterInput!): BoolFilter
}
type BoolFilter {
	id: ID!
	# many more, but only need id to make sure it's working
}
enum Operator {
	AND
	OR
	NOT
	XOR
}
type BoolFilterInput {
	operator: Operator!
	newFilters: [BoolFilterInput!] # termination case, stops recursing when newFilters is null
	existingFiltersIDs: [ID!]
	choiceIDs: [ID!]
}
```

**Here's what I have so far.**

`boolFilter.go`
```
type BoolFilterInput struct {
	Operator string
	NewFilters *[]*BoolFilterInput
	ExistingFilterIDs *[]string
	ChoiceIDs *[]string
}
```

`resolvers.go`
```
type Resolver struct {db: *sql.DB}

func (r *Resolver) CreateBoolFilter(args *struct { Input *BoolFilterInput } *BoolFilterResolver {
	tx, _ := r.db.Begin()
	id, _ := createNewBoolFilter(*newFilter, tx)
	_ = tx.Exec("INSERT ...", ...)
	_ = tx.Commit()
	return &BoolFilterResolver {db: r.db, id.String()}
}

func createNewBoolFilter(input BoolFilterInput, tx *sql.Tx) (uuid.UUID, error) {
	id := uuid.NewV1()
	var relevantIDs []uuid.UUID
	// ...
	if input.NewFilters != nil {
		for _, newFilter := range input.NewFilters {
			if newFilter != nil {
				id, _ := createNewBoolFilter(*newFilter, tx)
				relevantIDs = append(relevantIDs, id)
			}
		}
	}
	_, _ := tx.Exec("INSERT ... id & operator...", ...)
	for _, relevantID := range relevantIDs {
		_, _ := tx.Exec("INSERT ... id & relevantID", ...)
	}

	return id, nil
}
```

**What's happening**
The compiler is telling me contradictory things.
Depending on whether the type of `NewFilters` in `BoolFilterInput` is `*[]*BoolFilterInput`, `*[]BoolFilterInput`, or `[]BoolFilterInput`, it will tell me it's expecting a `pointer to a struct` or a `slice`. (It also wants `ExistingFilterIDs` and `ChoiceIDs` to be `[]string` even though both lists can be nullable, so my understanding is that both should be `*[]string`.

**Comment by neelance** [comment]
Same here. Please test again on latest master.

**Comment by neelance** [comment]
5b2978fcb1baf5d104a51d2638e2204abac0f5fd should fix this.

**Comment by EmperorEarth** [comment]
Looks like it's working

Will do more testing tomorrow to triple check

**Comment by EmperorEarth** [comment]
I've run this on recursions 4 levels deep that have >100 different references. As far as I can tell, 5b2978f works!
