### ISSUE TITLE
Ability to mask or exclude some opentracing variables

### ISSUE THREAD

**Issue by F21** [neelance/graphql-go#55]
When using opentracing, it will tag the variables being used for the request under `graphql.variables`. This is great for tracing and debugging, however, sometimes the information in a variable might be sensitive, for example, a password or perhaps even a credit card number.

It would be nice to be able to mask or exclude (in my case masking would be more useful) some of the variables, so that we can retain the ability to debug, but not have those pieces of information logged.

**Comment by neelance** [comment]
You mean `graphql.args.*`, right? Wouldn't it be possible to filter them similar to filtering trivial spans as described by https://github.com/neelance/graphql-go#opentracing?

**Comment by F21** [comment]
I am seeing them in 2 places: `graphql.variables` and `graphql.args.*`. I saw the filtering in the README, but it's not clear how to use a filter. Can you provide an example?

**Comment by F21** [comment]
Just some more thoughts on this. Filtering `graphql.args.*` should be simple, because we also have access to `graphql.field`, and `graphql.type`, so we can look at the field and type and then run the appropriate filtering algorithm for a given field and type.

In my case, I don't need to filter `graphql.args.*`, because my mutations only accept a single `Input` object as the argument as per the relay subscription: https://facebook.github.io/relay/docs/graphql-mutations.html#content

This ensures that when using it with variables, `graphql.args.input` = `input`.

However, filtering `graphql.variables` (which is what I need to do) is much more difficult. In this case, we only have the query string and the variables map, which makes it impossible to select which filtering algorithm to use for a given input type.

**Comment by neelance** [comment]
Hey @F21, graphql-go now has its own tracer type. The default is still to log to OpenTracing, but it can be more flexible now. Take a look at https://godoc.org/github.com/neelance/graphql-go/trace#Tracer. I've added a `varTypes` map to `TraceQuery`. I think you should be able to use this map to determine whether you want to filter a variable or not. For example you can create a custom scalar called `CreditCardNumber` and whenever a variable has that type you omit it from the trace. Beware of NonNull wrappers, unwrap them first before checking the name.

**Comment by F21** [comment]
@neelance Thanks you for implementing this! This is super useful and will make masking sensitive data much easier.

I have 2 questions:
- `ParseSchema` by default uses the OpenTracer tracer. I then set the tracer on the returned schema. Would it make sense to have a tracer argument for `ParseSchema`? This breaks backwards-compatibility though.

- Do you think it would be possible to pass the query name to `TraceQuery()`? By having access to the name of the query we can easily mask out the data without creating a lot of scalar types.

**Comment by neelance** [comment]
The tracer is an optional setting, just like the `MaxParallelism` setting. I don't want to bother people thinking about it when they just start using the library.

`TraceQuery` already has `operationName`, is that what you're looking for? Keep in mind that an operation name is much more likely to change than a type name `CreditCardNumber`.

**Comment by F21** [comment]
I believe `operationName` is something that is defined on the client side and can be empty if the client is not sending a query with multiple mutations. I was hoping I could get the name of the field in `TraceQuery`.

For example:
```graphql
{
  updateUserData(input: UpdateUserDataInput){
    updateDate
  }
}
```

If I could get the field name `updateUserData` in `TraceQuery`, then I can mask things in `variables` before tracing.

`TraceField` would not trace anything because variables are being used and it would just log `input` if the variables are sent as input.

**Comment by neelance** [comment]
`TraceQuery` is only executed once per query. There can be multiple top-level fields:
```
{
  updateUserData(input: ...){
    ...
  }
  updateFoo(input: ...){
    ...
  }
}
```

**Comment by neelance** [comment]
I just added `SchemaOpt`, now you pass the tracer to `ParseSchema`.

**Comment by F21** [comment]
@neelance Thanks! That's a great idea. This issue is probably resolved 😄
