### ISSUE TITLE
Can't pass array as variable field in mutation

### ISSUE THREAD

**Issue by jrryjcksn** [neelance/graphql-go#59]
Hello,
I'm trying to pass a variable to a mutation that contains an array of input objects but I keep getting rejected. My variables in my unit test:

				Variables: map[string]interface{}{
					"data": map[string]interface{}{
						"updatedUsers": []map[string]interface{}{map[string]interface{}{
							"id":       nextuser2,
							"isWriter": true,
							"isAdmin":  false}}}},

where the input object "data" is defined as: 

    # Input data to update an org
    input OrgUpdateInput {
       ....
        # Users to add
        updatedUsers: [OrgUserInput!]
    }
So, I'd like to pass any number of users to update. I get the following error: 

    	testing.go:35: graphql: graphql: panic occured: interface conversion: interface {} is []map[string]interface {}, not map[string]interface {}

In the single value case, I pass a "map[string]interface{}" and it works fine. Here it seems like I should pass a slice of said values. Am I doing something wrong?

Thanks for any help,
--Jerry Jackson

**Comment by neelance** [comment]
The `Variables` field expects the types according to how `enconding/json` decodes JSON, which means `[]interface{}`, not `[]map[string]interface{}`. Just change your line to `"updatedUsers": []interface{}{map[string]interface{}{` and it should work.

**Comment by jrryjcksn** [comment]
Fantastic! That fixed it. Thanks very much!
