### ISSUE TITLE
ToJSON() not in "data" 

### ISSUE THREAD

**Issue by amozoss** [neelance/graphql-go#67]
I expected schemaBuilder `ToJSON()` output to match the structure of http://graphql.org/learn/introspection/ with `__schema` being in a `data` object.

Expected: 
```
{
  "data": {
    "__schema": {
```
Got
```
{
    "__schema": {
```
Is there any reason not to have `ToJSON` return the `__schema` in a `data` object?

**Comment by neelance** [comment]
The practical reason is that not all GraphQL tools expect that additional `data` field. Also on the theoretical level there is not benefit at all in having it. You can add it in your code if you need it.

**Comment by amozoss** [comment]
Relay expects the `data` field, but I'm fine with wrapping it. Heres what I did if anyone runs across the same issue.
```
type DataWrapper struct {
        Data Schema `json:"data"`
}

type Schema struct {
        Schema map[string]interface{} `json:"__schema"`
}

func JSONInData(data []byte) ([]byte, error) {
        var schema Schema
        err := json.Unmarshal(data, &schema)
        if err != nil {
                return nil, err
        }
        wrapper := DataWrapper{
                Data: schema,
        }
        wrapped_data, err := json.Marshal(wrapper)
        if err != nil {
                return nil, err
        }
        return wrapped_data, nil
}
```
