### ISSUE TITLE
a new graphql server

### ISSUE THREAD

**Issue by bsr203** [neelance/graphql-go#7]
Just wanted to share a library introduced recently.

https://github.com/samsarahq/thunder

I am still exploring, and not sure anything we can learn from it.

**Comment by bsr203** [comment]
there is a lightning talk about it
https://www.youtube.com/watch?v=w2ZKEwfA7bM

**Comment by neelance** [comment]
@bsr203 Thanks for the information. Seems to me like the goals of the two projects are a bit different. I'll keep an eye on it.

**Comment by bsr203** [comment]
Indeed, it looks like the focus is more on live updates. There was mention about using reflection to define the schema, but didn't try. I will also make them aware of this library (it internally uses parts of https://github.com/graphql-go/graphql) so we have stronger community. thank you for all your work.
