### ISSUE TITLE
Can't use array of non-nullable type in mutations

### ISSUE THREAD

**Issue by zmb3** [neelance/graphql-go#78]
I can't seem to figure out how to accept an array of non-null items in a mutation.

Example schema:
```
input Link {
   name: String!
   url: String!
} 
type Mutation {
   addLinks(links: [Link!]) ID!
}
```

Notice that the `links` array itself is nullable, but the items in it should be non nullable.

My resolver:
```
func (r *Resolver) AddLinks(ctx context.Context, args *struct {
   Links *[]Link
}) (graphql.ID, error) {
// ...
}
```

When I try to parse the schema, I get `field "Links": expected pointer to struct, got Link returned by (*Resolver).AddLinks`

I've tried changing my schema to accept a non-nullable array of non-nullable elements:
```
   addLinks(links: [Link!]!) ID!
```

And then modifying my resolver to look for a plain slice, not a pointer:
```
func (r *Resolver) AddLinks(ctx context.Context, args *struct {
   Links []Link
}) (graphql.ID, error) {
// ...
}
```

And I get the same error.

I **can** get graphql-go to expect a slice instead of a struct pointer if I do something like this:
```
addLinks(links: [Link]!) ID!
```
But this (correctly) requires my resolver to accept a slice of pointers, which I'm trying to avoid.
```
args *struct { Links []*Link }
```

It's my understanding that:
 - `Type` in graphql maps to `*Type` in Go
 - `Type!` in graphql maps to `Type` in Go
 - `[Type]` in graphql maps to `*[]*Type` in Go 
 - `[Type]!` in graphql maps to `[]*Type` in Go ✅ 
 - `[Type!]!` in graphql maps to `[]Type` in Go ❌ 
 - `[Type!]` in graphql maps to `*[]Type` in Go ❌ 

The last two cases aren't working for me.

**Comment by mytototo** [comment]
I have the same issue. I can't work correctly with non-empty slice.
What's your workaround about slices? How do you handle pointers?

**Comment by tendolukwago** [comment]
@zmb3 did you ever find a resolution to your issue? or @neelance since you closed it out, do you have any words of wisdom on why we can't use an array of a non-nullable type? Any info would be much appreciated!

**Comment by neelance** [comment]
You should check if your resolver functions are defined on `Type` or `*Type` in Go. (Haven't touched this project for a while, just guessing).
