### ISSUE TITLE
custom scalar cannot be used as input

### ISSUE THREAD

**Issue by AAAton** [neelance/graphql-go#79]
Thank you for a nice piece of software. I started looking into custom scalars recently and noticed that the included custom `graphql.Time` type does not work as it did earlier. Has there been changes that I can't find documentation for?

Before f7d9ff4e09a02f4b09800eaf3604a36df90514e6 everything worked fine. I could send in both the Unix timestamp and the string-version. At this commit it started answering "wrong type" on requests. The test still works but I can't seem to use it in my application. 

At 95a4ecd841312e27b542fb147295923832fdc7bc the error message changes. It returns ```Argument "from" has invalid value 1490037177.
Expected type "Time", found 1490037177.```
The tests also works fine here. 

Do I need to implement the Time scalar myself nowadays? In what package would I place a custom type?

**Comment by tonyghita** [comment]
Check out the implementation of the `Time` scalar: https://github.com/neelance/graphql-go/blob/master/time.go

If that doesn't meet your needs, you can create one that does by following that example.

**Comment by AAAton** [comment]
That is the one that I'm using. But I can only get it to work up to commit f7d9ff4. After that it breaks.

**Comment by AAAton** [comment]
I now realize that I can return the custom scalar, but I am not able to use it as a filter or input:

```
{
  events {
    timestamp #works fine
  }
}
```
but this:
```
{
  events(from:123456789) {
    timestamp
  }
}
```
returns
`"message": "Argument \"from\" has invalid value 123456789.\nExpected type \"Time\", found 123456789."`

**Comment by tonyghita** [comment]
What does the `events` resolver look like?

**Comment by AAAton** [comment]
Toy example that doesn't work:

```
package main

import (
	"io/ioutil"
	"log"
	"net/http"

	"time"

	graphql "github.com/neelance/graphql-go"
	"github.com/neelance/graphql-go/relay"
)

var schema *graphql.Schema

func init() {
	var err error
	b, err := ioutil.ReadFile("schema.graphql")
	if err != nil {
		panic(err)
	}
	schema = graphql.MustParseSchema(string(b), &resolver{})
}

func main() {
	http.Handle("/query", &relay.Handler{Schema: schema})

	log.Fatal(http.ListenAndServe(":4040", nil))
}

type resolver struct{}

func (r *resolver) Events(args *struct{ From *graphql.Time }) *eventResolver {
	return &eventResolver{}
}

type eventResolver struct{}

func (r *eventResolver) Timestamp() graphql.Time {
	return graphql.Time{Time: time.Now()}
}
```

and the schema:
```
# Presents a RFC3339. Accepts Unix timestamps & RFC3339 
scalar Time

schema {
    query: RootQuery
}

type RootQuery {
    events(from: Time): Event
}

# Event based on an article 
type Event {
    # The time of the article
    timestamp: Time!
}
```

**Comment by hsyed** [comment]
I think I have hit a similar problem, the validator doesn't seem to make use of ` ImplementsGraphQLType(name string) bool` and `UnmarshalGraphQL(input interface{}) error ` to check if a scalar fits the schema.

**Comment by eknkc** [comment]
Ran into same / similar issue. When you run a query with embedded time like this:

```
{
  events(from: "2017-05-06T13:22:33.000Z") {
    timestamp
  }
}
```

it fails the validation but if you use a variable;

```
{
  events(from: $from) {
    timestamp
  }
}
```

and supply 

```json
{
  "from": "2017-05-06T13:22:33.000Z"
}
```

it works just fine.

**Comment by tonyghita** [comment]
I can reproduce the issue as well, FWIW. Digging through the code to try and understand a fix.

**Comment by tonyghita** [comment]
I've been digging through the validation code and found there is a missing check to determine whether an argument literal is coercible to its corresponding argument definition type.

The [specification](http://facebook.github.io/graphql/#sec-Compatible-Values) defines this check as:
> - For each _argument_ in the document
>   - Let _value_ be the Value of _argument_
>   - If _value_ is not a Variable
>      - Let _argumentName_ be the Name of _argument_.
>      - Let _argumentDefinition_ be the argument definition provided by the parent field or definition named _argumentName_.
>       - Let _type_ be the type expected by _argumentDefinition_.
>       - The type of _literalArgument_ must be coercible to _type_.

Given this specification, it seems like there should be a `default` case [on this switch statement](https://github.com/neelance/graphql-go/blob/f78108a335e635dffd75aa83a5f2114c1f76ca18/internal/validation/validation.go#L375-L393).

The default case then has the job of checking whether the argument literal can be coerced into the given type.

I think at the moment, the method does not have enough data to know whether a `*lexer.Literal` can be coerced into a `common.Type`. I'm not yet familiar enough with the project to know where such a lookup would exist (fingers crossed this gives @neelance an idea 😄 ).

**Comment by RXminuS** [comment]
@neelance Can you comment on @tonyghita's analysis, would love to help fix this but need some pointers
