### ISSUE TITLE
Can JWT token be accessed in the context obj in the resolver method?

### ISSUE THREAD

**Issue by LeeWong** [neelance/graphql-go#80]
Hi there,

I am passing JWT token in the request header but cannot figure out how to access in the resolver methods in this library. Could you please help me out? Thanks.

Cheers!

**Comment by tonyghita** [comment]
You could put it on the request context, and then extract the value from the context where you need it.

**Comment by neelance** [comment]
Exactly. So don't use the `relay` package, use a custom HTTP handler.

**Comment by LeeWong** [comment]
@tonyghita and @neelance Thanks. It works great now.
