### ISSUE TITLE
hangs when panic occurs

### ISSUE THREAD

**Issue by fzhangtj** [neelance/graphql-go#82]
Hi, I've encountered hanging when panic occurs in field selection.  It seems the bug is at /internal/exec/exec.go:

```
for _, f := range fields {
			go func(f *fieldWithResolver) {
				defer r.handlePanic(ctx)
				r.execFieldSelection(ctx, f.field, f.resolver, &f.out, false)
				wg.Done()
			}(f)
		}
```

wg.Done() will not be executed if panic occurs in r.execFieldSelection

**Comment by neelance** [comment]
Thanks for reporting.
