### ISSUE TITLE
Query with __typename returns nothing, how to fix it?

### ISSUE THREAD

**Issue by DenisNeustroev** [neelance/graphql-go#9]
I use Apollo client that automatically adds "__typename" field for each query. It is necessary for the internal optimisations and caching.

In your example this query works perfectly
```graphql
{
  hero {
    __typename
    id
  }
}
```
But this still returns nothing
```graphql
{
  human(id: "1000") {
    __typename
    id
  }
}
```

**Comment by neelance** [comment]
@DenisNeustroev Thanks for reporting!
