### ISSUE TITLE
How to pass values between resolvers

### ISSUE THREAD

**Issue by lpalmes** [neelance/graphql-go#95]
I've been using a lot this library (and i really enjoy it), and i'm moving my client side to relay.
I had a problem with the `viewer` pattern in relay, when trying to do the viewer pattern i can't pass values from my viewer resolver to my descendant resolvers.

```graphql
type Viewer {
   info: UserInfo,
   todos: [Todo]!
}
```
In this case i would like to pass to `todos` which user has made the request so i can respond with their todos only.

I was thinking about using context to pass additional values between resolvers, but i'm not really sure how given that i can only return a resolver and an optional error.

If you could guide me a bit with a solution it would be really helpful,
Thanks a lot and thanks for all the work in this package!

**Comment by neelance** [comment]
When you return a resolver you can have that resolver contain those values, couldn't you?

**Comment by lpalmes** [comment]
To be honest i feel dumb for not thinking about that. I've been trying this, it works great so far, thanks @neelance, i'm going to close this then.
